
# This is a sample pod yaml file
apiVersion: v1 
kind: Pod
metadata:
  name: ngninx-pod
  labels: 
    env: demo
    type: frontend
spec:
  containers:
   - name: nginx-container
     image: nginx
     ports:
      - containerPort: 80
