apiVersion: v1
kind: pod
metadata:
  name: myapp
  labels:
    name: myapp-pod
spec:
  containers:
    - name: myapp-container
      image: busybox:1.28
      env:
      - name: FIRSTNAME
        value: "piyush"
  initContainers:
    - name: init-myservice
      image: busybox:1.28
      command: ['sh','-c']
      args: ['until nslookup ']



